Repository dougUCN/LANE, pull requests merged in 2022-05, with the labels that each got.

#17 Add GraphQL Code Generator
  .gitignore
  README.md
  client/.eslintignore
  client/.eslintrc
  client/.gitignore
  client/codegen.yaml
  client/package-lock.json
  client/package.json
  client/src/App.graphql
  client/src/App.tsx
  client/src/index.tsx
Labels: documentation

#31 Add Styling to Navbar
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/components/Navbar.tsx
  client/src/components/Navigation.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/EMSPage.tsx
  client/tailwind.config.js
Labels: Ready for Review, FE

#30 Histogram Subscriptions
  .gitignore
  README.md
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/components/EMS.graphql
  client/src/components/EMS.tsx
  client/src/index.tsx
  server/data.sqlite3
  server/dependencies.txt
  server/histograms/common.py
  server/histograms/migrations/0001_initial.py
  server/histograms/models.py
  server/histograms/mutation.py
  server/histograms/query.py
  server/histograms/schema.graphql
  server/histograms/subscription.py
  server/liveData.sqlite3
  server/nEDM_server/schema.graphql
  server/slow_control/common.py
  server/slow_control/migrations/0001_initial.py
  server/slow_control/mutation.py
  server/slow_control/subscription.py
  server/tests/gqlComms.py
  server/tests/spoofLiveHist.py
  server/tests/spoofStaticHist.py
  server/users/users.sqlite3
Labels: Ready for Review, FE, BE

#33 Add python black
  .git-blame-ignore-revs
  .githooks/pre-commit
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  server/.gitignore
  server/dependencies.txt
  server/fast_daq_worker/tools/freq.py
  server/fast_daq_worker/tools/hist.py
  server/fast_daq_worker/tools/integrate.py
  server/fast_daq_worker/tools/scope.py
  server/fast_daq_worker/tools/scope_minmax.py
  server/histograms/common.py
  server/histograms/migrations/0001_initial.py
  server/histograms/models.py
  server/histograms/mutation.py
  server/histograms/query.py
  server/histograms/scalar.py
  server/histograms/subscription.py
  server/liveData.sqlite3
  server/nEDM_server/asgi.py
  server/nEDM_server/graphql_config.py
  server/nEDM_server/settings.py
  server/pyproject.toml
  server/slow_control/common.py
  server/slow_control/enum.py
  server/slow_control/messaging.py
  server/slow_control/migrations/0001_initial.py
  server/slow_control/models.py
  server/slow_control/mutation.py
  server/slow_control/query.py
  server/slow_control/subscription.py
  server/tests/gqlComms.py
  server/tests/spoofLiveHist.py
  server/tests/spoofStaticHist.py
  server/users/schema.py
  server/users/settings.py
Labels: Enhancement, Ready for Review

#34 Add additional fields to live histogram subscription
  client/src/components/EMS.graphql
  client/src/components/EMS.tsx
  server/histograms/schema.graphql
  server/histograms/subscription.py
  server/nEDM_server/schema.graphql
Labels: Ready for Review, FE, BE

#36 EMS - Add Live Charts
  client/package-lock.json
  client/package.json
  client/src/components/EMS.graphql
  client/src/components/EMS.tsx
  client/src/components/EMS/EMS.graphql
  client/src/components/EMS/EMS.tsx
  client/src/components/EMS/HistogramChart.tsx
  client/src/components/EMS/hooks/useChart.tsx
  client/src/pages/EMSPage.tsx
  server/data.sqlite3
  server/histograms/common.py
  server/histograms/migrations/0001_initial.py
  server/histograms/models.py
  server/histograms/query.py
  server/histograms/scalar.py
  server/histograms/schema.graphql
  server/histograms/subscription.py
  server/nEDM_server/schema.graphql
  server/slow_control/migrations/0001_initial.py
  server/tests/gqlComms.py
  server/tests/spoofLiveHist.py
  server/tests/spoofStaticHist.py
  server/users/users.sqlite3
Labels: Ready for Review, FE, BE

#38 Refactor EMS Page
  client/package-lock.json
  client/package.json
  client/src/components/EMS/EMS.tsx
  client/src/components/EMS/HistogramChart.tsx
  client/src/components/EMS/hooks/useChart.tsx
  client/src/components/EMS/hooks/useStateFromProps.tsx
  client/src/components/EMS/index.tsx
  client/src/components/Navbar/Navbar.tsx
  client/src/components/Navbar/StyledLink.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/shared/Button.tsx
  client/src/index.tsx
  client/src/pages/EMSPage.tsx
Labels: Ready for Review, FE

#41 Fix datetime scalar issue + add BE unit tests
  .github/workflows/mainPR.yml
  server/histograms/query.py
  server/histograms/scalar.py
  server/nEDM_server/schema.graphql
  server/test/gqlComms.py
  server/test/spoofLiveHist.py
  server/test/spoofStaticHist.py
  server/test/test_static_histogram.py
  server/test/test_suite.py
Labels: Enhancement, Ready for Review, BE

#43 Add Logo and Favicon
  client/.eslintignore
  client/.eslintrc.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/favicon/favicon-192x192.png
  client/public/favicon/favicon-32x32.png
  client/public/index.html
  client/public/logo/lane-dark-no-bg-A.png
  client/public/logo/lane-dark-no-bg-B.png
  client/public/logo/lane-dark.png
  client/public/logo/lane-light-no-bg.png
  client/public/logo/lane-light.png
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/components/EMS/EMS.tsx
  client/src/components/Navbar/Navbar.tsx
  client/src/hooks/useDarkMode/index.tsx
  client/src/hooks/useDarkMode/useDarkMode.tsx
  client/src/hooks/useDarkMode/usePrefersDarkMode.tsx
  client/src/hooks/useDarkMode/useSafeLocalStorage.tsx
  client/tailwind.config.js
Labels: Ready for Review, FE

#44 Remove broken JWT api
  server/dependencies.txt
  server/nEDM_server/graphql_config.py
  server/nEDM_server/schema.graphql
  server/nEDM_server/settings.py
  server/users/README.md
  server/users/schema.graphql
  server/users/schema.py
  server/users/settings.py
Labels: Ready for Review, BE
